// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetHostnameHandlerFunc turns a function with the right signature into a get hostname handler
type GetHostnameHandlerFunc func(GetHostnameParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetHostnameHandlerFunc) Handle(params GetHostnameParams) middleware.Responder {
	return fn(params)
}

// GetHostnameHandler interface for that can handle valid get hostname params
type GetHostnameHandler interface {
	Handle(GetHostnameParams) middleware.Responder
}

// NewGetHostname creates a new http.Handler for the get hostname operation
func NewGetHostname(ctx *middleware.Context, handler GetHostnameHandler) *GetHostname {
	return &GetHostname{Context: ctx, Handler: handler}
}

/*GetHostname swagger:route GET /hostname getHostname

GetHostname get hostname API

*/
type GetHostname struct {
	Context *middleware.Context
	Handler GetHostnameHandler
}

func (o *GetHostname) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetHostnameParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
